
version: 2.1


jobs:

  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hello, world! from group 4" > echo-output.txt
      - persist_to_workspace:
          root: .
          paths:
            - echo-output.txt

  print-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: cat echo-output.txt
      

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - print-hello:
          requires:
            - say-hello
